on:
  workflow_dispatch:

jobs:
  createserver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Template
        uses: actions/checkout@main

      - name: Login
        uses: azure/login@v1
        with:
          creds: $({secrets.AZURE_CREDS})

      - name: Deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: 297bb58d-ff69-447c-8c7b-9414b5634677
          resourceGroupName: Rg-Cloud-VigneshVaka
          template: ../templates/staticwebapp.json
